CREATE TABLE IF NOT EXISTS incidents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description CLOB NOT NULL,
    severity VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS diagnoses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_id BIGINT REFERENCES incidents(id),
    suggested_root_cause CLOB NOT NULL,
    remediation_steps CLOB NOT NULL,
    confidence VARCHAR(50) NOT NULL,
    verification VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS runbook_fragments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content CLOB NOT NULL,
    tags CLOB,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS incident_embeddings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_id BIGINT REFERENCES incidents(id),
    text CLOB NOT NULL,
    embedding VARBINARY,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS runbook_embeddings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fragment_id BIGINT REFERENCES runbook_fragments(id),
    text CLOB NOT NULL,
    embedding VARBINARY,
    created_at TIMESTAMP NOT NULL
);
